# Generated by Django 6.0.4 on 2026-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_anonymouse',
            field=models.BooleanField(default=False),
        ),
    ]
