# Generated by Django 6.0.3 on 2026-04-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
