# Generated by Django 6.0.3 on 2026-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_phone_created_at_alter_phone_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
